version: "3.5"

services:

    zookeeper:
        image: confluentinc/cp-zookeeper
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181

    kafka:
        build:
            context: .
            dockerfile: Dockerfile.kafka
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
