version: "3.5"

services:

    zookeeper:
        image: confluentinc/cp-zookeeper
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181

    broker:
        build:
            context: .
            dockerfile: Dockerfile.kafka
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2

    rest_proxy:
        image: confluentinc/cp-kafka-rest
        environment:
            - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_REST_HOST_NAME=rest_proxy
