version: "3.5"

services:

    zookeeper:
        image: confluentinc/cp-zookeeper
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181

    broker:
        build:
            context: .
            dockerfile: Dockerfile.kafka
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2

    rest_proxy:
        image: confluentinc/cp-kafka-rest
        environment:
            - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_REST_HOST_NAME=rest_proxy

    control_center:
        image: confluentinc/cp-control-center
        environment:
            - CONTROL_CENTER_ZOOKEEPER_CONNECT=zookeeper:2181
            - CONTROL_CENTER_REPLICATION_FACTOR=1
            - CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=1
            - CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1
            - CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS=2
        ports:
            - 38000:9021

    ui:
        image: landoop/kafka-topics-ui
        environment:
            KAFKA_REST_PROXY_URL: http://rest_proxy:8082/
            PROXY: "true"
        ports:
            - 38001:8000
